name: Generate Sitemap

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */2 * * *'  # Runs every 2 hours

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests  # Install required packages for your script

      - name: Generate Sitemap
        run: python generate_sitemap.py

      - name: Commit and push sitemap
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add sitemap.xml
          git commit -m "Update sitemap"
          git push